---
title: "Currency exchange model in mycorrhizae associations"
author: "J. Hillert"
date: "`r Sys.Date()`"
output:
  bookdown::word_document2:
    number_sections: false
    toc: no
    always_allow_html: true

bibliography:
- aRticles.bib

csl: ecology.csl
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE,
                      echo=FALSE,
                      warning=FALSE)

library(papaja)
library(tidyverse)


papaja::r_refs(file = "paper4.bib")

options(knitr.kable.NA = "")


```

There are several forms of mycorrhizae with whom plants are able to associate and exchange nutrients, each partner supplying a resource for trade. These associations can range from endophytic - where the fungus gains excess Carbon (C) and the plant is neutrally affected, to exploitative as is the case for fungus and orchids. Association with mycorrhizae comes with costs and benefits to both the host and the symbiont. In endophytic associations, the fungus gains C and habitat while the plant is neutrally affected. In balanced associations, each partner gives up a resource in exchange for another imposing a cost and benefit on both parties. Lastly, in exploitative associations with orchids, the host receives mineral nutrients and a mechanism for seed germination, while the symbiont receives no benefit and grows just as well with a host as without. Research that uses currency exchange models provide more detail about the association between host and symbiont. These associations are then affected by spatial and temporal scales that affect the nutrient exchange.

Mycorhizzae associations are proposed to begin with endophytic associations, upon increased commitment and specialization between partners the association advances toward a balanced association [@Brun2002]. These initial associations are either positive-neutral or positive-negative, in benefit to the symbiont and cost to the host. Benefits for the symbiont include greater access to excess plant C, first access to the host upon death, and evasion of competition, predation, and parasitism by other organisms. Plant benefits are either, neutral and likely to evolve into protection from more harmful fungi or a negative harmful association that would be selected against evolutionarily. Balanced associations develop from endophytic associations to exchange hosts excess C for excess mineral nutrients in the symbiont. The exchange occurs in an interface zone where each partner must overcome barriers to maintain the association and avoid cheaters. Exploitative associations, i.e. orchid mycorhizae, occur when the host is fully reliant on the symbiont for mineral nutrients, seed germination, and - for chorophyll-lacking orchids - organic C assimilated by the symbiont. These are not yet fully understood associations as the symbiont is able to survive as well with the host as without. 

These associations will face biotic and abiotic barriers that both partners will have to overcome to maintain their line of benefit. Nutrients are rarely evenly distributed in nature and nutrient heterogeneity provides mechanisms for evolotion to select for or against. Mycorrhizae alter how plant roots forage for nutrients and plants are able to allocate between its roots and fungal hyphae [@Chen2018]. In associations with trees, thinner roots forage more efficiently than thick roots. The costs and benefits of mycorrhizae association depends on nutrient turnover rate, C use efficiency, and differences in nutrient uptake between plant roots and fungal hyphae. Arbuscular mycorrhizae (AMF) primarily acquire mineral nutrients - Nitrogen, Phosphorus, and amino acids [@Chen2018; @Wein2019] - and are able to forage more precisely than ectomycorrhizal fungi. Ectomycorrhizal fungi (EMF) have superior capacity to decompose simple substrates and rely more on mychorrizae [@Chen2018]. Foraging efficiency between AMF, EMF, and non-mycorrhizae associations supply selective pressures to maximize benefits over costs. On the symbiont side, costs are minimized when fungal exudates are not harmful to the host while benefits are maximized upon receiving excess host C, habitat for the fungus, and inheritance from one generation to the next. 

Mutualistic symbiosis with mycorrhiza has three elements; currency, mechanism of exchange, and mechanism of symbiont inheritance. Fungal associations can be inherited horizontally by acquiring new symbionts from the environment or vertically inherited from host parent to host offspring. Whether these associations persist affects associations on a generational scale. @Wein2019 found that  transmission first inheritance arises under neutral or near neutral conditions where the symbiosis gradually becomes beneficial. On the other end of inheritance, currency first arises from a provisional need for nutrients where beneficial associations are positively selected for to maintain the symbiosis. Associations with mycorrhizae falter if one partner the exchange is no longer beneficial, in which case the exchange becomes nonfunctional and selective pressure is against the association. When a limited resource becomes abundant, the currency is not as valuable and any excess may become harmful to the host. Lastly, if symbionts are not inherited to offspring then there will be competition between fungi for access to the offspring host. Mutualism is a sensitive process and advancements in one partner need to be reflected in the other for the symbiosis to persist. Further research on this topic could look at associations between orchids and fungi. How is this association beneficial for the symbiont? Why does the symbiosis persist if the symbiont recieves no benefit? Further research about symbiotic associations can provide answers to these questions and reveal more about how mycorrhizae maintain a potentially costly association with orchids.


# References






























